# See https://houndci.com/configuration for help.
javascript:
  enabled: true
  config_file: .js-style.json
ruby:
  enabled: true
  config_file: .ruby-style.yml
scss:
  enabled: true
  config_file: .scss-style.json
