Style/NumericLiterals:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/Next:
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: true

Style/TrailingCommaInArguments:
  Enabled: true

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false
