data:
  read:
    - config/locales/%{locale}.yml
    - config/locales/**/*.%{locale}.yml

ignore_unused:
 - 'date.*'
 - 'simple_form.*'
 - 'time.*'
 - 'titles.*'
 - 'will_paginate.page_entries_info.*'

ignore_missing:
 - simple_form.*
